---
# Bring stack down
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained # no traffic at all

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become:  true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 state=started

# Bring stack up
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=restarted
    - wait_for: port=80

- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=restarted
    - wait_for: port=80